/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package visao;

/**
 *
 * @author ejmcc
 */
public class TelaPrincipal extends javax.swing.JFrame {

  /**
   * Creates new form TelaPrincipal
   */
  public TelaPrincipal() {
    initComponents();
    this.setLocationRelativeTo(null);
  }

  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        JButton_Servicos = new javax.swing.JButton();
        JButton_Gastos = new javax.swing.JButton();
        JButton_Veiculo = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Serif", 1, 50)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Mecanica Jedi");

        JButton_Servicos.setBackground(new java.awt.Color(1, 79, 89));
        JButton_Servicos.setFont(new java.awt.Font("Helvetica Neue", 3, 14)); // NOI18N
        JButton_Servicos.setForeground(new java.awt.Color(255, 255, 255));
        JButton_Servicos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/figuras/servico.png"))); // NOI18N
        JButton_Servicos.setText("Menu Servíços");
        JButton_Servicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButton_ServicosActionPerformed(evt);
            }
        });

        JButton_Gastos.setBackground(new java.awt.Color(1, 79, 89));
        JButton_Gastos.setFont(new java.awt.Font("Helvetica Neue", 3, 14)); // NOI18N
        JButton_Gastos.setForeground(new java.awt.Color(255, 255, 255));
        JButton_Gastos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/figuras/real-brasileiro (1).png"))); // NOI18N
        JButton_Gastos.setText("Menu Gastos");
        JButton_Gastos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButton_GastosActionPerformed(evt);
            }
        });

        JButton_Veiculo.setBackground(new java.awt.Color(1, 79, 89));
        JButton_Veiculo.setFont(new java.awt.Font("Helvetica Neue", 3, 14)); // NOI18N
        JButton_Veiculo.setForeground(new java.awt.Color(255, 255, 255));
        JButton_Veiculo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/figuras/frota.png"))); // NOI18N
        JButton_Veiculo.setText("Menu Veículos");
        JButton_Veiculo.setBorder(null);
        JButton_Veiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JButton_VeiculoActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/figuras/Logo-sith-empire (1).png"))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(28, 28, 28)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 353, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(JButton_Servicos, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JButton_Gastos, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JButton_Veiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(116, 116, 116))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel1)))
                .addGap(31, 31, 31)
                .addComponent(JButton_Gastos, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(JButton_Veiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(JButton_Servicos, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(81, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

  private void JButton_GastosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButton_GastosActionPerformed
    // TODO add your handling code here:
    TelaGastos janelaGastos = new TelaGastos();
    janelaGastos.setVisible(true);
    dispose();
  }//GEN-LAST:event_JButton_GastosActionPerformed

  private void JButton_VeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButton_VeiculoActionPerformed
    // TODO add your handling code here:
    TelaVeiculoProprietario janelaVeicProp = new TelaVeiculoProprietario();
    janelaVeicProp.setVisible(true);
    dispose();
  }//GEN-LAST:event_JButton_VeiculoActionPerformed

  private void JButton_ServicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JButton_ServicosActionPerformed
    // TODO add your handling code here:
    TelaServicos janelaServicos = new TelaServicos();
    janelaServicos.setVisible(true);
    dispose();
  }//GEN-LAST:event_JButton_ServicosActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new TelaPrincipal().setVisible(true);
      }
    });
  }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JButton_Gastos;
    private javax.swing.JButton JButton_Servicos;
    private javax.swing.JButton JButton_Veiculo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
