/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package visao;
import modelos.Servicos;
import modelos.IServicosCRUD;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import persistencia.*;

/**
 *
 * @author ejmcc
 */
public class TelaServicos extends javax.swing.JFrame {
  private IServicosCRUD servicosBD = null;
  /**
   * Creates new form TelaServicos
   */
  public TelaServicos() {
    initComponents();
    setLocationRelativeTo(null);
    try {
      servicosBD = new ServicosDAO();
      mostrarServicosNaGrid();
    } catch (Exception erro) {
      JOptionPane.showMessageDialog(null, "Construtor Tela: "+erro.getMessage());
    }
    
  }
  private void limparTela(){
    jTextFieldId.setText("");
    jTextFieldDescricao.setText("");
  }
  private void mostrarServicosNaGrid(){
  try {
    ArrayList<Servicos> listaDeServicos = null;
    listaDeServicos = servicosBD.obterListaDeServicos();
    DefaultTableModel model =  (DefaultTableModel) jTableServicos.getModel();
    model.setNumRows(0); 
    if(listaDeServicos.isEmpty()) 
      throw new Exception("Lista de Servicos BD Vazia");
    for(int pos = 0; pos < listaDeServicos.size(); pos++){
      Servicos objServico = listaDeServicos.get(pos);
      String[] linha = new String[2];
      linha[0]= objServico.getIdentificador() + "";
      linha[1]= objServico.getDescricao();
      model.addRow(linha);
    }  
  } catch (Exception erro) {
      JOptionPane.showMessageDialog(rootPane, erro.getMessage());
    }    
}
  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jLabel1 = new javax.swing.JLabel();
    jLabel2 = new javax.swing.JLabel();
    jTextFieldId = new javax.swing.JTextField();
    jLabel3 = new javax.swing.JLabel();
    jTextFieldDescricao = new javax.swing.JTextField();
    jButtonIncluir = new javax.swing.JButton();
    jButtonAlterar = new javax.swing.JButton();
    jScrollPane1 = new javax.swing.JScrollPane();
    jTableServicos = new javax.swing.JTable();
    jButtonVoltar = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
    setTitle("SERVIÇOS");

    jLabel1.setFont(new java.awt.Font("Helvetica Neue", 3, 36)); // NOI18N
    jLabel1.setText("CADASTRO DE SERVIÇOS");

    jLabel2.setFont(new java.awt.Font("Helvetica Neue", 3, 18)); // NOI18N
    jLabel2.setText("IDENTIFICADOR");

    jTextFieldId.setFont(new java.awt.Font("Helvetica Neue", 3, 18)); // NOI18N

    jLabel3.setFont(new java.awt.Font("Helvetica Neue", 3, 18)); // NOI18N
    jLabel3.setText("DESCRIÇÃO");

    jTextFieldDescricao.setFont(new java.awt.Font("Helvetica Neue", 3, 18)); // NOI18N

    jButtonIncluir.setFont(new java.awt.Font("Helvetica Neue", 3, 18)); // NOI18N
    jButtonIncluir.setText("INCLUIR");
    jButtonIncluir.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButtonIncluirActionPerformed(evt);
      }
    });

    jButtonAlterar.setFont(new java.awt.Font("Helvetica Neue", 3, 18)); // NOI18N
    jButtonAlterar.setText("ALTERAR");
    jButtonAlterar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButtonAlterarActionPerformed(evt);
      }
    });

    jTableServicos.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
    jTableServicos.setModel(new javax.swing.table.DefaultTableModel(
      new Object [][] {
        {null, null},
        {null, null},
        {null, null},
        {null, null}
      },
      new String [] {
        "IDENTIFICADOR", "DESCRIÇÃO"
      }
    ) {
      boolean[] canEdit = new boolean [] {
        false, false
      };

      public boolean isCellEditable(int rowIndex, int columnIndex) {
        return canEdit [columnIndex];
      }
    });
    jScrollPane1.setViewportView(jTableServicos);
    if (jTableServicos.getColumnModel().getColumnCount() > 0) {
      jTableServicos.getColumnModel().getColumn(0).setResizable(false);
      jTableServicos.getColumnModel().getColumn(1).setResizable(false);
    }

    jButtonVoltar.setFont(new java.awt.Font("Helvetica Neue", 3, 18)); // NOI18N
    jButtonVoltar.setForeground(new java.awt.Color(153, 0, 0));
    jButtonVoltar.setText("VOLTAR");
    jButtonVoltar.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButtonVoltarActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addComponent(jLabel1)
        .addGap(106, 106, 106))
      .addGroup(layout.createSequentialGroup()
        .addGap(33, 33, 33)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
          .addGroup(layout.createSequentialGroup()
            .addComponent(jLabel3)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jTextFieldDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, 479, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGroup(layout.createSequentialGroup()
            .addComponent(jLabel2)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jTextFieldId, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGroup(layout.createSequentialGroup()
            .addComponent(jButtonIncluir)
            .addGap(18, 18, 18)
            .addComponent(jButtonAlterar)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jButtonVoltar))
          .addComponent(jScrollPane1))
        .addContainerGap(26, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(21, 21, 21)
        .addComponent(jLabel1)
        .addGap(46, 46, 46)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel2)
          .addComponent(jTextFieldId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(18, 18, 18)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jLabel3)
          .addComponent(jTextFieldDescricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(35, 35, 35)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(jButtonIncluir)
          .addComponent(jButtonAlterar)
          .addComponent(jButtonVoltar))
        .addGap(18, 18, 18)
        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addContainerGap(70, Short.MAX_VALUE))
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

  private void jButtonIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIncluirActionPerformed
    try {
      int identificador = 0;
      String descricao = jTextFieldDescricao.getText();
      Servicos objServico = new Servicos(identificador, descricao);
      servicosBD.incluir(objServico);
      limparTela();
      mostrarServicosNaGrid();
    } catch (Exception erro) {
      JOptionPane.showMessageDialog(rootPane, "Incluir Visao: "+erro.getMessage());
    }
  }//GEN-LAST:event_jButtonIncluirActionPerformed

  private void jButtonAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAlterarActionPerformed
    try {
      int identificador = Integer.parseInt(jTextFieldId.getText());
      String descricao = jTextFieldDescricao.getText();
      Servicos objServico = new Servicos(identificador, descricao);
      servicosBD.alterar(objServico);
      limparTela();
      mostrarServicosNaGrid();
    } catch (Exception erro) {
      JOptionPane.showMessageDialog(rootPane, "Incluir Visao: "+erro.getMessage());
    }
  }//GEN-LAST:event_jButtonAlterarActionPerformed

  private void jButtonVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVoltarActionPerformed
    // TODO add your handling code here:
    TelaPrincipal janelaPrincipal = new TelaPrincipal();
    janelaPrincipal.setVisible(true);
    dispose();
  }//GEN-LAST:event_jButtonVoltarActionPerformed

  /**
   * @param args the command line arguments
   */
  public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
      for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Nimbus".equals(info.getName())) {
          javax.swing.UIManager.setLookAndFeel(info.getClassName());
          break;
        }
      }
    } catch (ClassNotFoundException ex) {
      java.util.logging.Logger.getLogger(TelaServicos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
      java.util.logging.Logger.getLogger(TelaServicos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
      java.util.logging.Logger.getLogger(TelaServicos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
      java.util.logging.Logger.getLogger(TelaServicos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
      public void run() {
        new TelaServicos().setVisible(true);
      }
    });
  }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton jButtonAlterar;
  private javax.swing.JButton jButtonIncluir;
  private javax.swing.JButton jButtonVoltar;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel2;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JTable jTableServicos;
  private javax.swing.JTextField jTextFieldDescricao;
  private javax.swing.JTextField jTextFieldId;
  // End of variables declaration//GEN-END:variables
}
